<?php
function smiley($quote) {

$code = array();
$code[0] = "/:determined/";
$code[1] = "/:disappoint/";
$code[2] = "/:impossibru/";
$code[3] = "/:mouthopen/";
$code[4] = "/:openmouth/";
$code[5] = "/:badpoker/";
$code[6] = "/:newstear/";
$code[7] = "/:tdadjump/";
$code[8] = "/:awesome/";
$code[9] = "/:cochran/";
$code[10] = "/:disgust/";
$code[11] = "/:friends/";
$code[12] = "/:kidding/";
$code[13] = "/:popcorn/";
$code[14] = "/:redeyes/";
$code[15] = "/:aliens/";
$code[16] = "/:badass/";
$code[17] = "/:cereal/";
$code[18] = "/:datash/";
$code[19] = "/:hehehe/";
$code[20] = "/:notbad/";
$code[21] = "/:picard/";
$code[22] = "/:pickle/";
$code[23] = "/:racket/";
$code[24] = "/:tongue/";
$code[25] = "/:wasted/";
$code[26] = "/:wizard/";
$code[27] = "/:dance/";
$code[28] = "/:dolan/";
$code[29] = "/:ewbte/";
$code[30] = "/:happy/";
$code[31] = "/:notok/";
$code[32] = "/:poker/";
$code[33] = "/:smirk/";
$code[34] = "/:steve/";
$code[35] = "/:water/";
$code[36] = "/:baby/";
$code[37] = "/:baww/";
$code[38] = "/:clap/";
$code[39] = "/:deal/";
$code[40] = "/:derp/";
$code[41] = "/:down/";
$code[42] = "/:dude/";
$code[43] = "/:flip/";
$code[44] = "/:fuuu/";
$code[45] = "/:fyea/";
$code[46] = "/:gasp/";
$code[47] = "/:grin/";
$code[48] = "/:gtfo/";
$code[49] = "/:herp/";
$code[50] = "/:high/";
$code[51] = "/:milk/";
$code[52] = "/:mind/";
$code[53] = "/:ohno/";
$code[54] = "/:rage/";
$code[55] = "/:rich/";
$code[56] = "/:sadm/";
$code[57] = "/:side/";
$code[58] = "/:spit/";
$code[59] = "/:stfi/";
$code[60] = "/:susp/";
$code[61] = "/:tdad/";
$code[62] = "/:what/";
$code[63] = "/:yuno/";
$code[64] = "/:act/";
$code[65] = "/:all/";
$code[66] = "/:fal/";
$code[67] = "/:fap/";
$code[68] = "/:fff/";
$code[69] = "/:fum/";
$code[70] = "/:gay/";
$code[71] = "/:god/";
$code[72] = "/:lie/";
$code[73] = "/:lod/";
$code[74] = "/:lol/";
$code[75] = "/:mad/";
$code[76] = "/:ogw/";
$code[77] = "/:pff/";
$code[78] = "/:sad/";
$code[79] = "/:wat/";
$code[80] = "/:why/";
$code[81] = "/:win/";
$code[82] = "/:wut/";
$code[83] = "/:yam/";
$code[84] = "/:yao/";
$code[85] = "/:ay/";
$code[86] = "/:ca/";
$code[87] = "/:ce/";
$code[88] = "/:et/";
$code[89] = "/:fa/";
$code[90] = "/:fg/";
$code[91] = "/:he/";
$code[92] = "/:jc/";
$code[93] = "/:mg/";
$code[94] = "/:no/";
$code[95] = "/:np/";
$code[96] = "/:ok/";
$code[97] = "/:sd/";
$code[98] = "/:sh/";
$code[99] = "/:st/";
$code[100] = "/:th/";
$code[101] = "/:ts/";
$code[102] = "/:ub/";
$code[103] = "/:up/";
$code[104] = "/:m/";
$code[105] = "/:t/";

$img = array();
$img[0] = "<img src=\"troll/determined.png\" alt=\"!determined\" />";
$img[1] = "<img src=\"troll/iamdisappointed.png\" alt=\"!disappoint\" />";
$img[2] = "<img src=\"troll/impossibru.png\" alt=\"!impossibru\" />";
$img[3] = "<img src=\"troll/mouthopen.png\" alt=\"!mouthopen\" />";
$img[4] = "<img src=\"troll/openmouth.png\" alt=\"!openmouth\" />";
$img[5] = "<img src=\"troll/badpokerface.png\" alt=\"!badpoker\" />";
$img[6] = "<img src=\"troll/newspaperguytear.png\" alt=\"!newstear\" />";
$img[7] = "<img src=\"troll/tdadjump.png\" alt=\"!tdadjump\" />";
$img[8] = "<img src=\"troll/awesome.png\" alt=\"!awesome\" />";
$img[9] = "<img src=\"troll/cochran.gif\" alt=\"!cochran\" />";
$img[10] = "<img src=\"troll/disgusted.png\" alt=\"!disgust\" />";
$img[11] = "<img src=\"troll/friends.png\" alt=\"!friends\" />";
$img[12] = "<img src=\"troll/kidding.png\" alt=\"!kidding\" />";
$img[13] = "<img src=\"troll/popcorn.gif\" alt=\"!popcorn\" />";
$img[14] = "<img src=\"troll/redeyes.png\" alt=\"!redeyes\" />";
$img[15] = "<img src=\"troll/aliens.jpg\" alt=\"!aliens\" />";
$img[16] = "<img src=\"troll/badass.png\" alt=\"!badass\" />";
$img[17] = "<img src=\"troll/cereal.png\" alt=\"!cereal\" />";
$img[18] = "<img src=\"troll/datash.jpg\" alt=\"!datash\" />";
$img[19] = "<img src=\"troll/hehehe.png\" alt=\"!hehehe\" />";
$img[20] = "<img src=\"troll/notbad.jpg\" alt=\"!notbad\" />";
$img[21] = "<img src=\"troll/picard.png\" alt=\"!picard\" />";
$img[22] = "<img src=\"troll/pickle.png\" alt=\"!pickle\" />";
$img[23] = "<img src=\"troll/racket.jpg\" alt=\"!racket\" />";
$img[24] = "<img src=\"troll/tongue.png\" alt=\"!tongue\" />";
$img[25] = "<img src=\"troll/wasted.png\" alt=\"!wasted\" />";
$img[26] = "<img src=\"troll/wizard.png\" alt=\"!wizard\" />";
$img[27] = "<img src=\"troll/dance.gif\" alt=\"!dance\" />";
$img[28] = "<img src=\"troll/dolan.png\" alt=\"!dolan\" />";
$img[29] = "<img src=\"troll/ewbte.png\" alt=\"!ewbte\" />";
$img[30] = "<img src=\"troll/happy.png\" alt=\"!happy\" />";
$img[31] = "<img src=\"troll/itsnotokay.png\" alt=\"!notok\" />";
$img[32] = "<img src=\"troll/pokerface.png\" alt=\"!poker\" />";
$img[33] = "<img src=\"troll/smirk.jpg\" alt=\"!smirk\" />";
$img[34] = "<img src=\"troll/steve.jpg\" alt=\"!steve\" />";
$img[35] = "<img src=\"troll/waterbottle.jpg\" alt=\"!water\" />";
$img[36] = "<img src=\"troll/babytroll.png\" alt=\"!baby\" />";
$img[37] = "<img src=\"troll/baww.png\" alt=\"!baww\" />";
$img[38] = "<img src=\"troll/citizen_cane.gif\" alt=\"!clap\" />";
$img[39] = "<img src=\"troll/dealwithit.gif\" alt=\"!deal\" />";
$img[40] = "<img src=\"troll/derp.png\" alt=\"!derp\" />";
$img[41] = "<img src=\"troll/down.png\" alt=\"!down\" />";
$img[42] = "<img src=\"troll/dudecomeon.png\" alt=\"!dude\" />";
$img[43] = "<img src=\"troll/flip.png\" alt=\"!flip\" />";
$img[44] = "<img src=\"troll/fffuuu.png\" alt=\"!fuuu\" />";
$img[45] = "<img src=\"troll/fuckyea.png\" alt=\"!fyea\" />";
$img[46] = "<img src=\"troll/gasp.png\" alt=\"!gasp\" />";
$img[47] = "<img src=\"troll/biggrin.png\" alt=\"!grin\" />";
$img[48] = "<img src=\"troll/gtfo.png\" alt=\"!gtfo\" />";
$img[49] = "<img src=\"troll/herpderp.png\" alt=\"!herp\" />";
$img[50] = "<img src=\"troll/high.png\" alt=\"!high\" />";
$img[51] = "<img src=\"troll/milk.png\" alt=\"!milk\" />";
$img[52] = "<img src=\"troll/mindblown.gif\" alt=\"!mind\" />";
$img[53] = "<img src=\"troll/ohno.png\" alt=\"!ohno\" />";
$img[54] = "<img src=\"troll/rage2.png\" alt=\"!rage\" />";
$img[55] = "<img src=\"troll/fu.png\" alt=\"!rich\" />";
$img[56] = "<img src=\"troll/sadmelvin.png\" alt=\"!sadm\" />";
$img[57] = "<img src=\"troll/sidemouth.png\" alt=\"!side\" />";
$img[58] = "<img src=\"troll/cerealspitting.png\" alt=\"!spit\" />";
$img[59] = "<img src=\"troll/stfi.jpg\" alt=\"!stfi\" />";
$img[60] = "<img src=\"troll/suspicious.png\" alt=\"!susp\" />";
$img[61] = "<img src=\"troll/trolldad.png\" alt=\"!tdad\" />";
$img[62] = "<img src=\"troll/what.png\" alt=\"!what\" />";
$img[63] = "<img src=\"troll/yuno.png\" alt=\"!yuno\" />";
$img[64] = "<img src=\"troll/actually.png\" alt=\"!act\" />";
$img[65] = "<img src=\"troll/all.png\" alt=\"!all\" />";
$img[66] = "<img src=\"troll/falbulous.gif\" alt=\"!fal\" />";
$img[67] = "<img src=\"troll/fapfap.png\" alt=\"!fap\" />";
$img[68] = "<img src=\"troll/fullpanel.png\" alt=\"!fff\" />";
$img[69] = "<img src=\"troll/fumanchu.jpg\" alt=\"!fum\" />";
$img[70] = "<img src=\"troll/gaytroll.png\" alt=\"!gay\" />";
$img[71] = "<img src=\"troll/god.png\" alt=\"!god\" />";
$img[72] = "<img src=\"troll/lied.png\" alt=\"!lie\" />";
$img[73] = "<img src=\"troll/lod.jpg\" alt=\"!lod\" />";
$img[74] = "<img src=\"troll/lolnotext.png\" alt=\"!lol\" />";
$img[75] = "<img src=\"troll/mad.png\" alt=\"!mad\" />";
$img[76] = "<img src=\"troll/ogw.png\" alt=\"!ogw\" />";
$img[77] = "<img src=\"troll/pffftcchchchhfffttt.png\" alt=\"!pff\" />";
$img[78] = "<img src=\"troll/sad.png\" alt=\"!sad\" />";
$img[79] = "<img src=\"troll/wat.jpg\" alt=\"!wat\" />";
$img[80] = "<img src=\"troll/whywithhands.png\" alt=\"!why\" />";
$img[81] = "<img src=\"troll/somuchwin.png\" alt=\"!win\" />";
$img[82] = "<img src=\"troll/wut.png\" alt=\"!wut\" />";
$img[83] = "<img src=\"troll/yam.png\" alt=\"!yam\" />";
$img[84] = "<img src=\"troll/yaoming.png\" alt=\"!yao\" />";
$img[85] = "<img src=\"troll/awyeah.png\" alt=\"!ay\" />";
$img[86] = "<img src=\"troll/challengeaccepted.png\" alt=\"!ca\" />";
$img[87] = "<img src=\"troll/closeenough.png\" alt=\"!ce\" />";
$img[88] = "<img src=\"troll/excitedtroll.png\" alt=\"!et\" />";
$img[89] = "<img src=\"troll/foreveralone.png\" alt=\"!fa\" />";
$img[90] = "<img src=\"troll/feelsgood.png\" alt=\"!fg\" />";
$img[91] = "<img src=\"troll/highexpectations.jpg\" alt=\"!he\" />";
$img[92] = "<img src=\"troll/jackiechan.jpg\" alt=\"!jc\" />";
$img[93] = "<img src=\"troll/megusta.png\" alt=\"!mg\" />";
$img[94] = "<img src=\"troll/no.png\" alt=\"!no\" />";
$img[95] = "<img src=\"troll/newspaperguy.png\" alt=\"!np\" />";
$img[96] = "<img src=\"troll/okay.png\" alt=\"!ok\" />";
$img[97] = "<img src=\"troll/staredad.png\" alt=\"!sd\" />";
$img[98] = "<img src=\"troll/shocked.png\" alt=\"!sh\" />";
$img[99] = "<img src=\"troll/sadtroll.png\" alt=\"!st\" />";
$img[100] = "<img src=\"troll/thoughtful.png\" alt=\"!th\" />";
$img[101] = "<img src=\"troll/truestory.png\" alt=\"!ts\" />";
$img[102] = "<img src=\"troll/underbite.png\" alt=\"!ub\" />";
$img[103] = "<img src=\"troll/upvote.png\" alt=\"!up\" />";
$img[104] = "<img src=\"troll/melvin.png\" alt=\"!m\" />";
$img[105] = "<img src=\"troll/problem.png\" alt=\"!t\" />";


  return preg_replace($code, $img, $quote);

}
?>
